default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: event_planner_development

test:
  <<: *default
  database: event_planner_test

production:
  <<: *default
  database: event_planner_production
  username: event_planner
  password: <%= ENV['EVENT_PLANNER_DATABASE_PASSWORD'] %>
